### ISSUE TITLE
Redunding command

### ISSUE THREAD

**Issue by Raphael-Boichot** [zenaro147/NeoGB-Printer#16]
This commands in config.h.txt
#define BMP_UPSCALE_FACTOR 1    //Set the Upscale factor for the BMP output (Set 0 to disable)
#define PNG_UPSCALE_FACTOR 1    //Set the Upscale factor for the PNG output (Set 0 to disable)

Is redunding with:

"bmpimage": {
    "scale":1
  },
  "pngimage": {
    "scale":1
  }

In conf.json

**Comment by zenaror** [comment]
@Raphael-Boichot Technically, no. (at least in my head)

the config.h will be used as default value in the NeoGBP. So, especially if the conf.json doesn't exist, the NeoGBP will create the conf.json based in the config.h values at first time.

The conf.json parameters are fully customizable and will replace the config.h values. The idea is prevent to re-upload the arduino code for each change.

for example: if one day you just want to output as PNG only, for example, you just need to set the bmpimage>scale to 0 in the conf.json, instead upload the whole code again. the same idea if you want to mess around with the scale factors
