### ISSUE TITLE
Does the GBA link cable PCB need any special parameters?

### ISSUE THREAD

**Issue by mainrs** [zenaro147/NeoGB-Printer#24]
https://oshpark.com/shared_projects/srSgm3Yj

I am referring to these:
![image](https://user-images.githubusercontent.com/5113257/193932396-b29a4560-792a-4509-a8df-3ea6d2e7d922.png)

**Comment by zenaror** [comment]
Hi @mainrs 
For tge PBC, the GBA cable can use the same parameters as the GB/GBC cable.

But be careful... normally the GBA cable connection is way different as the standard GB/GBC cable, for example, 1P SI on GBA cable, normally is connected to the GND line, and the SO from 2P is not connected to the 1P SI... that's not how the GB/GBC cable works. (Also I saw some "adaptations" using two 4player cables to be able to use the pins correctly, but I never tested)

That's how the GBA cable connection normally looks like http://www.mks.purespace.de/technical/gbm08.gif

You can always check the connections using a multimeter.

**Comment by mainrs** [comment]
Thanks for the reply! What I meant was if I have to check one of the options when ordering the GameBoy Link Cable Breakout board mentioned [here](https://github.com/zenaro147/NeoGB-Printer/wiki/List-of-Materials#optional-components) on the Wiki.

There is no mention that the thicker copper layer is needed. And I have no clue if the After Dark option does anything from a functional perspective.

**Comment by zenaror** [comment]
> Thanks for the reply! What I meant was if I have to check one of the options when ordering the GameBoy Link Cable Breakout board mentioned [here](https://github.com/zenaro147/NeoGB-Printer/wiki/List-of-Materials#optional-components) on the Wiki.
> 
> There is no mention that the thicker copper layer is needed. And I have no clue if the After Dark option does anything from a functional perspective.

You can leave all these OSH optional features unchecked as well… I bought mine like this and they work fine for both cables and systems.

**Comment by mainrs** [comment]
Thank you very much! I will definitely have to take a closer look when it comes to wiring. I thought the printer only supported GBA. It sounds like you got both ports on yours.

**Comment by zenaror** [comment]
> Thank you very much! I will definitely have to take a closer look when it comes to wiring. I thought the printer only supported GBA. It sounds like you got both ports on yours.

You're welcome 😁
Feel free to ask other thing about it!

But yeah, this Gameboy Printer Emulator should works on GB/GBC and GBA as well. (And some homebrews)
Here you can check the compatible games https://github.com/zenaro147/NeoGB-Printer/wiki/Compatible-Games
It should supports every each game officially launched during their lifetime.

**Comment by mainrs** [comment]
Out of curiosity, do certain games require special code? or do all the games use the same protocol to communicate with the printer?

**Comment by zenaror** [comment]
> Out of curiosity, do certain games require special code? or do all the games use the same protocol to communicate with the printer?

It's the same protocol for every game... but some games made different usages for the commands... (for example... some games send a margin parameter into the printer command... but other games send a full white data command to simulate a margin)

But essentially they always use the same commands
