### ISSUE TITLE
Issue with Pokemon Pinball Score

### ISSUE THREAD

**Issue by zenaror** [zenaro147/NeoGB-Printer#26]
Apparently, after some while, the game checks the printer connection sending some "init commands'

No bin file is saved, but this causes some bugs on printer, like wrong File count and some corrupted score print bins.

**Comment by Mraulio** [comment]
The highscore screen has a pop-up where it checks if the printer is connected, sending INIT commands. It doesn't save any bin file, but if you leave it sending those INIT and after a while you print it causes some issues.
While sending those INIT commands, the printer changes between Idle and Hex - > bin.

https://user-images.githubusercontent.com/12874082/206929260-7e2f235b-1091-4bc4-9e48-386a8b0e769b.mp4

**Comment by Mraulio** [comment]
https://user-images.githubusercontent.com/12874082/206929206-5d8ce040-6f1f-4c8f-993f-d74fcd5f903a.mp4

**Comment by Raphael-Boichot** [comment]
Issue closed, code fixed.
