### ISSUE TITLE
Custom PCB Link no longer works

### ISSUE THREAD

**Issue by pocketprintersnaps** [zenaro147/NeoGB-Printer#31]
clicking on the custom PCB link will send you to this
![Immagine](https://github.com/user-attachments/assets/a86d64e7-ce67-4cdf-9fcc-4e16579a04a2)

**Comment by mofosyne** [comment]
You looking for https://github.com/zenaro147/NeoGB-Printer/tree/master/NeoGB_Printer_PCB ?

**Comment by pocketprintersnaps** [comment]
I think it's that one, yes! For some reason the link on the main page is broken!

**Comment by zenaror** [comment]
@mofosyne  is right!

Thanks to report the broken link ❤️

I will fix that in a minute!

Recently I merged some repositories and probably forgot to fix some links 😅

**Comment by zenaror** [comment]
I fixed the links :D
let me know if you find some other links broken :)
