### ISSUE TITLE
Issues with SD card access on ESP32 board versions 2.0.0, 2.0.1 and 2.0.2

### ISSUE THREAD

**Issue by 6d64** [zenaro147/NeoGB-Printer#9]
I could not get the SD card mounting on my ESP32 when compiled using ESP32 board version 2.0.0 and above. It took me a while to work out what the issue was, until everything suddenly started working when I soldered an SD card to VSPI pins.

This is not an issue in NeoGB-Printer itself though - there are several upstream issues in ESP32 libraries with SD card access via HSPI, I found at least these three:

- espressif/arduino-esp32#6162
- espressif/arduino-esp32#6189
- espressif/arduino-esp32#6295

I believe that 2.0.3-RC1 includes some of these fixes, and I had some success running NeoGB-Printer on that version, but I found that 1.0.6 worked the best.

I think it would be great to update the [Software Setup wiki page](https://github.com/zenaro147/NeoGB-Printer/wiki/Software-Setup) to  suggest using 1.0.6, at least until 2.0.3 is released.

**Comment by zenaro147** [comment]
Hi @6d64

First of all, thanks so much for the PRs!
I'll check then as soon as possible to merge then into the main code!

About this SD issue, I already saw some SD issues with the ESP32 boards (Btw if you can tell me your board, I can add it to the "compatible boards list" to help new users)... So you are you basically using the SD card with the VSPI and the Link Cable with HSPI? How you set up the thing?

This is pretty important, especially with the PCB project 😁

**Comment by zenaror** [comment]
> I could not get the SD card mounting on my ESP32 when compiled using ESP32 board version 2.0.0 and above. It took me a while to work out what the issue was, until everything suddenly started working when I soldered an SD card to VSPI pins.
> 
> This is not an issue in NeoGB-Printer itself though - there are several upstream issues in ESP32 libraries with SD card access via HSPI, I found at least these three:
> 
> * [Fix - SD mount issue espressif/arduino-esp32#6162](https://github.com/espressif/arduino-esp32/pull/6162)
> * [SD card stops working after updating arduino-esp32 from ver. 1.0.6 to ver 2.0.2  espressif/arduino-esp32#6189](https://github.com/espressif/arduino-esp32/issues/6189)
> * [ESP32 using SD card with HSPI works at full speed under 1.0.6, fails or runs very slowly under 2.0.2 espressif/arduino-esp32#6295](https://github.com/espressif/arduino-esp32/issues/6295)
> 
> I believe that 2.0.3-RC1 includes some of these fixes, and I had some success running NeoGB-Printer on that version, but I found that 1.0.6 worked the best.
> 
> I think it would be great to update the [Software Setup wiki page](https://github.com/zenaro147/NeoGB-Printer/wiki/Software-Setup) to suggest using 1.0.6, at least until 2.0.3 is released.

Hi @6d64 !

First of all, thanks so much for the PRs!
I'll check then as soon as possible to merge them into the main code!

About this SD issue, I already saw some SD issues with the ESP32 boards (Btw if you can tell me your board, I can add it to the "compatible boards list" to help new users)... So are you using the SD card with the VSPI and the Link Cable with HSPI? How did you set up the thing?

I'll test here the 1.0.6 version too, I'm only waiting for my new pieces to arrive to make more tests.

This is pretty important, especially with the PCB project 😁

(Btw, we're accepting pics for the user setups)

**Comment by zenaror** [comment]
@6d64 Thanks for the tip about the version!
it really fix my SD issue hahahaha
I thought it was my SD module! hahaha

I added this note in the documentation!

Really thanks for the tip!

I'll let this issue opened until the ESP team relase a fix for it !

**Comment by 6d64** [comment]
Hi @zenaro147, sorry, I meant that I only used the VSPI pins to work out what the problem was, just to check if my ESP32 board was faulty, which is what lead me to work out that the issue is in the ESP32 libraries :-D In the end, I was able to use the SD card on HSPI pins by switching to 1.0.6.

I will confirm the exact ESP32 board version in the next 5 days (by 2022-04-20) and will provide an update on this issue. I have however already modified my board slightly - I have removed the USB protection diode between VIN and USB +5V power, as it was dropping voltage to 4.4V on the VIN pin and I wasn't sure if the voltage drop would cause any issues in communication. I believe that the board I am using has a different pinout to the one in [Raphael's setup](https://github.com/zenaro147/NeoGB-Printer/blob/master/showcase/RaphaelBOICHOT.jpg).

(PS thanks so much for all your work on this project and making it public - it's really great to be able to use all of printer functionality on old Gameboys, looking forward to the PCB designs!)

**Comment by zenaror** [comment]
> Hi @zenaro147, sorry, I meant that I only used the VSPI pins to work out what the problem was, just to check if my ESP32 board was faulty, which is what lead me to work out that the issue is in the ESP32 libraries :-D In the end, I was able to use the SD card on HSPI pins by switching to 1.0.6.

Oooh I got it 😁. Recently I've got the same issue in my board... This version change save my life hahaha. Many thanks! (Unfortunately I can't cancel the order now, or even a refund hahaha)

> I will confirm the exact ESP32 board version in the next 5 days (by 2022-04-20) and will provide an update on this issue. I have however already modified my board slightly - I have removed the USB protection diode between VIN and USB +5V power, as it was dropping voltage to 4.4V on the VIN pin and I wasn't sure if the voltage drop would cause any issues in communication. I believe that the board I am using has a different pinout to the one in [Raphael's setup](https://github.com/zenaro147/NeoGB-Printer/blob/master/showcase/RaphaelBOICHOT.jpg).

No problem! Feel free to share any mod or further setup you have 😁
Is there any special reason to remove the regulator?
My board and the Raphael's board are the same (some generic one). And we have some tests using a LiliGo board (I can't remember the model now). And since there is a lot of boards, that's why is important to make a list of "working" models.

> (PS thanks so much for all your work on this project and making it public - it's really great to be able to use all of printer functionality on old Gameboys, looking forward to the PCB designs!)

I'm glad that this project can be helpful to other people, as it be for me.
Especially because I don't actually have a Gameboy Printer (And it's not that easy to find in my country, even import the product), so... We need to make a "way" to use the features hahaha.
And to be honest I didn't expect a community collaboration too soon! Your PR's kinda surprised me! 😁
Huge thanks!

**Comment by 6d64** [comment]
> My board and the Raphael's board are the same (some generic one). And we have some tests using a LiliGo board (I can't remember the model now). And since there is a lot of boards, that's why is important to make a list of "working" models.

Hi @zenaro147, well, I am not sure about the exact version of my board, it's only labelled "ESP32S" on the underside, and the pinout and layout match [this one](https://www.mischianti.org/2021/02/17/doit-esp32-dev-kit-v1-high-resolution-pinout-and-specs/) exactly. So I think my board is a generic clone of the 30-pin DOIT ESP32 DevKit V1 board. Looking at the [picture](https://github.com/zenaro147/NeoGB-Printer/blob/master/showcase/RaphaelBOICHOT.jpg), you have the longer 38-pin board that matches [this pinout](https://wiki.joanillo.org/images/thumb/a/ab/ESP32-38-Pin-Pinout.jpg/600px-ESP32-38-Pin-Pinout.jpg).

> Is there any special reason to remove the regulator?

Not really, I just removed it out of caution. I believe that the diode is there to protect the USB connection, because the dev kit can be powered by up to 20 volts on the VIN pin, so the diode isolates USB +5V from VIN. But if you are powering the ESP32 from USB, then the VIN pin will only get 4.4V on it. I replaced the diode with a bridged connection so that I would get full 5V on the VIN pin, just because I wasn't sure if lower voltage would have caused any issues with the level shifter.

**Comment by zenaror** [comment]
> > My board and the Raphael's board are the same (some generic one). And we have some tests using a LiliGo board (I can't remember the model now). And since there is a lot of boards, that's why is important to make a list of "working" models.
> 
> Hi @zenaro147, well, I am not sure about the exact version of my board, it's only labelled "ESP32S" on the underside, and the pinout and layout match [this one](https://www.mischianti.org/2021/02/17/doit-esp32-dev-kit-v1-high-resolution-pinout-and-specs/) exactly. So I think my board is a generic clone of the 30-pin DOIT ESP32 DevKit V1 board. Looking at the [picture](https://github.com/zenaro147/NeoGB-Printer/blob/master/showcase/RaphaelBOICHOT.jpg), you have the longer 38-pin board that matches [this pinout](https://wiki.joanillo.org/images/thumb/a/ab/ESP32-38-Pin-Pinout.jpg/600px-ESP32-38-Pin-Pinout.jpg).

Our board is an ESP-Wroom-32, with 38 pins... I'm using as a DOIT ESP into the Arduino IDE... And Raphael's as a Generic Dev module. Both works here.

30 pins should works fine too...I think in the worst scenario, you can use the VSPI with the SD card, and another 3 random pins to the Link Cable (it was bitBang, the emulator don't use any SPI library).

But like I said, just make sure it's a dual core module, some Esp32 S (like the S2) has only one core, but the S3 has two now (I think there is some tests you can make to discover this info), otherwise it won't work (unfortunately we didn't manage to work with single core in our boards, all because the ESP can't write and handle the incoming bytes in the same core, since it uses interrupt to capture the bytes from the GB)


> > Is there any special reason to remove the regulator?
> 
> Not really, I just removed it out of caution. I believe that the diode is there to protect the USB connection, because the dev kit can be powered by up to 20 volts on the VIN pin, so the diode isolates USB +5V from VIN. But if you are powering the ESP32 from USB, then the VIN pin will only get 4.4V on it. I replaced the diode with a bridged connection so that I would get full 5V on the VIN pin, just because I wasn't sure if lower voltage would have caused any issues with the level shifter.

Ooh, I got it. It makes sense now. So, currently I'm powering with an external 5v source, so I'll keep my regulator in place 😅

**Comment by zenaror** [comment]
@6d64 Apparently they fixed the SD now
